name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create config file
        run: |
          echo "const config = {" > config.js
          echo "  firebase: {" >> config.js
          echo "    apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> config.js
          echo "    authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> config.js
          echo "    projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> config.js
          echo "    storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> config.js
          echo "    messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> config.js
          echo "    appId: '${{ secrets.FIREBASE_APP_ID }}'," >> config.js
          echo "    measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'" >> config.js
          echo "  }" >> config.js
          echo "};" >> config.js
          ls -la
          cat config.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
